//
//  APIMacroSupport.swift
//  NetworkActor
//
//  Created by Marcos del Castillo Camacho on 15/06/2026.
//

import Foundation

// MARK: - Main Macro

/// Transforms a protocol into a fully-functional API client struct.
///
/// Parameter roles are detected by **naming convention**:
/// - `body` (internal name) → JSON-encoded request body
/// - `query` (external name) → named query parameter
/// - Type `[URLQueryItem]` → query items array passed directly
/// - `header` (external name) → dynamic HTTP header
/// - Matches `{name}` in path → path parameter (string-interpolated)
///
/// Usage:
/// ```swift
/// @API(
///     host: URLs.api,
///     headers: APIConstants.headers,
///     client: Client(session: URLSessions.shared, certificates: APIConstants.certificates),
///     auth: AuthManager.shared,
///     crash: CrashManager.shared,
/// )
/// protocol AlertsAPI {
///     @Get("/alerts")
///     func list() async throws -> [AlertDto]
///
///     @Post("/alerts")
///     func create(body: AlertDto) async throws -> AlertDto
///
///     @Delete("/alerts/{id}")
///     func remove(id: Int) async throws
///
///     @Get("/offers")
///     func search(query page: Int, query limit: Int) async throws -> OffersDto
/// }
/// ```
@attached(peer, names: suffixed(Client))
public macro API(
    host: String,
    base: String = "",
    headers: [String: String] = [:],
    client: Any,
    auth: Any? = nil,
    crash: Any? = nil
) = #externalMacro(module: "BeamMacros", type: "APIMacro")

// MARK: - HTTP Method Markers

/// GET endpoint. Path params use `{name}` syntax.
@attached(peer)
public macro Get(_ path: String, task: _TaskKind = .data, headers: [String: String] = [:], auth: AuthPolicy = .required) = #externalMacro(module: "BeamMacros", type: "GetMacro")

/// POST endpoint.
@attached(peer)
public macro Post(_ path: String, task: _TaskKind = .data, headers: [String: String] = [:], auth: AuthPolicy = .required) = #externalMacro(module: "BeamMacros", type: "PostMacro")

/// PUT endpoint.
@attached(peer)
public macro Put(_ path: String, task: _TaskKind = .data, headers: [String: String] = [:], auth: AuthPolicy = .required) = #externalMacro(module: "BeamMacros", type: "PutMacro")

/// DELETE endpoint.
@attached(peer)
public macro Delete(_ path: String, task: _TaskKind = .data, headers: [String: String] = [:], auth: AuthPolicy = .required) = #externalMacro(module: "BeamMacros", type: "DeleteMacro")

/// PATCH endpoint.
@attached(peer)
public macro Patch(_ path: String, task: _TaskKind = .data, headers: [String: String] = [:], auth: AuthPolicy = .required) = #externalMacro(module: "BeamMacros", type: "PatchMacro")

/// HEAD endpoint.
@attached(peer)
public macro Head(_ path: String, task: _TaskKind = .data, headers: [String: String] = [:], auth: AuthPolicy = .required) = #externalMacro(module: "BeamMacros", type: "HeadMacro")

/// OPTIONS endpoint.
@attached(peer)
public macro Options(_ path: String, task: _TaskKind = .data, headers: [String: String] = [:], auth: AuthPolicy = .required) = #externalMacro(module: "BeamMacros", type: "OptionsMacro")

/// CONNECT endpoint.
@attached(peer)
public macro Connect(_ path: String, task: _TaskKind = .data, headers: [String: String] = [:], auth: AuthPolicy = .required) = #externalMacro(module: "BeamMacros", type: "ConnectMacro")

/// TRACE endpoint.
@attached(peer)
public macro Trace(_ path: String, task: _TaskKind = .data, headers: [String: String] = [:], auth: AuthPolicy = .required) = #externalMacro(module: "BeamMacros", type: "TraceMacro")

/// WebSocket endpoint. Opens a persistent bidirectional connection (GET + upgrade).
@attached(peer)
public macro Socket(_ path: String, headers: [String: String] = [:], auth: AuthPolicy = .required) = #externalMacro(module: "BeamMacros", type: "SocketMacro")

// MARK: - Supporting Types

/// Task kind marker for route macros.
public enum _TaskKind: Sendable {
    case data
    case upload
    case download
}

// MARK: - Runtime Configuration Container

/// Stores the shared configuration generated by `@API`.
public struct _APIConfiguration: Sendable {
    public let host: String
    public let base: String
    public let components: [any RequestComponent]

    public init(host: String, base: String, components: [any RequestComponent]) {
        self.host = host
        self.base = base
        self.components = components
    }
}
